@tool
extends Object
class_name TerravoltCatalogMeta
## Generated by scripts/catalog-sync.mjs — do not edit by hand.

const CATALOG_VERSION := "0.17.0"
const REGISTRY_SHA256 := "74a86433ab397a7e0abca61f7dcf6f9beaf053cf2c7aaa842844d643ebd60130"
