@tool
extends Object
class_name TerraVoltCatalogMeta
## Generated by scripts/catalog-sync.mjs — do not edit by hand.

const CATALOG_VERSION := "0.12.0"
const REGISTRY_SHA256 := "970959903139e6794b74d5acf1e980b86b0a1236e01e217e73c79c435e800f5c"
