@tool
extends Object
class_name TerraVoltCatalogMeta
## Generated by scripts/catalog-sync.mjs — do not edit by hand.

const CATALOG_VERSION := "0.12.0"
const REGISTRY_SHA256 := "431772cd65645aabb201cc9eacae7682640e44eff114400d142faceb87406b70"
