/**
 * Sync shared method registry SHA256 into Godot addon _generated/catalog_meta.gd
 * so server.info can expose catalog_version + registry_sha256 for tools.health.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const regPath = join(root, "packages/shared/methods/registry.json");
const outDir = join(root, "packages/godot-mcp-addon/_generated");
const outPath = join(outDir, "catalog_meta.gd");

const bytes = readFileSync(regPath);
const hash = createHash("sha256").update(bytes).digest("hex");
const { catalog_version: catalogVersion } = JSON.parse(bytes.toString("utf8"));

mkdirSync(outDir, { recursive: true });

const gd = `@tool
extends Object
class_name TerraVoltCatalogMeta
## Generated by scripts/catalog-sync.mjs — do not edit by hand.

const CATALOG_VERSION := "${catalogVersion}"
const REGISTRY_SHA256 := "${hash}"
`;

writeFileSync(outPath, gd, "utf8");
process.stdout.write(`catalog-sync: ${outPath} (${catalogVersion} ${hash.slice(0, 12)}…)\n`);
