import { mkdirSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(repoRoot, "artifacts", "js-graphs");
const depConfig = join(repoRoot, "config", "dependency-cruiser.config.cjs");

mkdirSync(outDir, { recursive: true });

writeFileSync(
  join(outDir, "README.md"),
  `# JS module graphs (Omni toolchain)

Generated by \`npm run intel:graphs\` (dependency-cruiser + madge).

| File | Source |
|------|--------|
| **dependency-graph.json** | dependency-cruiser |
| **madge-graph.json** | madge (circularity / module summary) |

MCP reference clones under \`references/godot-mcp-*\` are scanned; **\`references/godot-docs/\`** (Sphinx) is excluded. \`artifacts/\` and \`graphify-out/\` stay excluded.

Refresh \`docs/repo-layout.md\` / \`docs/architecture/overview.md\` when product layout under \`packages/\` changes materially.
`,
  "utf8",
);

try {
  execSync(
    `npx depcruise --config "${depConfig}" -T json -f "${join(outDir, "dependency-graph.json")}" .`,
    { cwd: repoRoot, stdio: "inherit", shell: true },
  );
} catch {
  console.warn(
    "[intel:graphs] dependency-cruiser reported issues or no matching files — see output above.",
  );
}

try {
  const exclude = "(references/godot-docs|node_modules|artifacts|graphify-out|\\.git)";
  const out = execSync(
    `npx madge . --extensions ts,tsx,js,jsx,mjs,cjs --exclude "${exclude}" --json`,
    { cwd: repoRoot, encoding: "utf8", shell: true },
  );
  writeFileSync(join(outDir, "madge-graph.json"), out, "utf8");
} catch {
  writeFileSync(
    join(outDir, "madge-graph.json"),
    JSON.stringify(
      {
        info: "madge could not build graph (no JS/TS modules yet or parse issue)",
      },
      null,
      2,
    ),
    "utf8",
  );
}

console.log("[intel:graphs] finished");
